name: main_pr

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  call-reusable:
    uses: j-moralejo-pinas/ci-cd-python/.github/workflows/main_pr.yml@367643d5a90bab6a2df1fff6671a25b548501527
    secrets: inherit
