name: publish_on_tag

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  call-reusable:
    uses: j-moralejo-pinas/ci-cd-python/.github/workflows/publish_on_tag.yml@367643d5a90bab6a2df1fff6671a25b548501527
    secrets: inherit
